### ISSUE TITLE
newer version

### ISSUE THREAD

**Issue by jrudess** [Damianonymous/MFCAuto#1]
Thought you might be interested in v5.6.2.  Link is only valid for 48 hours (can reupload if needed):
https://volafile.org/get/BkJziIn_6gB4u/MFCAuto.v5.6.2.tar.gz

**Comment by Damianonymous** [comment]
I am sorry that I did not notice this topic. I did not expect anyone to write, I'm not a programmer, I only share the archive of deleted applications. I do not know if I understood correctly because I do not know English, if you need a hlssession plugin written by back-to, then I've added the archive of plug-ins.

**Comment by jrudess** [comment]
No worries, if you don't mind, I've pointed streamdvr to your hosting of MFCAuto so that its easier for people to get working again.   Thats the only reason I wanted to send you the latest version. :-)
